on: [push]



jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.3
        with:
          username: 'root'
          server: 'cudostrona.pl'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './tree/gh-pages/*'
          remote_path: '/var/www/my_webapp/www/'
          delete_remote_files: true