on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftps.cudostrona.pl
        port: 22
        protocol: ftps
        username: my_webapp
        password: ${{ secrets.ftp.password }}
        #server-dir: www/
        #local-dir: public/
