on: push
name: Publish Website Dry Run
jobs:
  web-deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.1.0

    - name: 📂 Sync files
      uses: SamKirkland/web-deploy@1.0.0
      with:
        ftp-server: cudostrona.pl
        ftp-username: my_webapp
        ftp-password: ${{ secrets.PASSWORD }}
        source-path: ./www/
        